### ISSUE TITLE
fill out column B "measurement location" in META-Room automatically

### ISSUE THREAD

**Issue by gabroko** [IEA-EBC-Annex86/annex#3]
should be possible based on config file/sheet (measurement location ist in ID/columnA)

**Comment by retostauffer** [comment]
@gabroko 

Implemented for version `0.2` (see note below). Same as for #4. Questionable how useful this is as it is duplicated information (the last part of the ID corresponds to the room type/name). 

![meta-room](https://user-images.githubusercontent.com/13628564/210219364-541fc9ca-a8c0-43ed-bd21-c2627e6e138a.png)

One idea would be to write a "long name", e.g., `Bedroom` if it is for `Bed`. This is, however, not good from a programming perspective as a user could change one part but not update the other one - this would require additional checks/tests. Or simply leave this column out as the ID is fairly readable and is the unique key for everything.

**Testing development version**

If you want to test the development version you need to check out the correct branch (not yet in main branch). You can do so by calling:

```
install_github("IEA-EBC-Annex86/annex", ref = "version_0.2")    # Installs latest version of the version_0.2 branch
```

**Comment by gabroko** [comment]
good point, duplicate information, maybe we use this field for optional additional information regarding the location ("near the window", "on the ceiling", "on kitchen counter", etc.). In many cases there is additional information regarding the measurement location. The field comments in this sheet could then be for arbritrary additional information.

**Comment by retostauffer** [comment]
Code adjusted, closing this now.
