### ISSUE TITLE
fill out column B "pollutant name" in META-Pollutant (now META-Variable) automatically

### ISSUE THREAD

**Issue by gabroko** [IEA-EBC-Annex86/annex#4]
should be possible, since info is in column A (ID)

**Comment by retostauffer** [comment]
@gabroko 

Implemented for version `0.2` (see note below). Questionable how useful this is as it is duplicated information (the last part of the ID corresponds to the variable name). 

![meta-variable](https://user-images.githubusercontent.com/13628564/210218855-001aa3ec-4840-496c-bace-714559336f28.png)

One idea would be to write a "long name", e.g., `Relative Humidity` if it is for `RH`. This is, however, not good from a programming perspective as a user could change one part but not update the other one - this would require additional checks/tests. Or simply leave this column out as the ID is fairly readable and is the unique key for everything.

**Testing development version**

If you want to test the development version you need to check out the correct branch (not yet in main branch). You can do so by calling:

```
install_github("IEA-EBC-Annex86/annex", ref = "version_0.2")    # Installs latest version of the version_0.2 branch
```

**Comment by gabroko** [comment]
yes, agree, could be omitted

**Comment by retostauffer** [comment]
Code adjusted; following the same idea as for 'META-Room' (see #3) by (i) not duplicating the information but (ii) allow the user to add additional (optional) information if needed.
