### ISSUE TITLE
add info / guidance on choosing the right time zone when preparing data

### ISSUE THREAD

**Issue by gabroko** [IEA-EBC-Annex86/annex#6]
instructions now show example with transforming to POSIX in tz=UTC, this might lead to the conclusion that all dataframes must be in UTC. But timezone of the raw data should be provided. E.g. include link or list for the most common abbriviations.

**Comment by retostauffer** [comment]
Good point; we should show an example on how to properly use a local time zone (maybe demonstrate it with European Central Time with the demo data set).

As there are about 40 different time zones in use, a link to an external resource might be better than listing them.
