### ISSUE TITLE
annex_validate: differentiate between must have entries (error/hard warning) and nice to have entries (soft warning)

### ISSUE THREAD

**Issue by gabroko** [IEA-EBC-Annex86/annex#7]
Must haves:
Study: Contact, Year
Home: Country, Ventilation type
Room: -
Variable: unit (here it would be nice if we could limit to a drop down, that is defined in definitions?) and additional info for certain pollutants
Season and Time sheets can be removed

**Comment by retostauffer** [comment]
I've improved the validation and implemented soft and hard checks; to be discussed @gabroko. Currently only in the `devel` branch and not open for testing.

The tests need to be modified as I mostly focused on the implementation so far but is easily adjustable.

**Comment by retostauffer** [comment]
This has been addressed in release `0.2-4`; no major user response/issues so far, thus closing this issue.
